server:
  port: 8082
  servlet:
    context-path: /product
spring:
  application:
    name: spring-cloud-product
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
