server:
  port: 8081
  servlet:
    context-path: /auth
spring:
  application:
    name: spring-cloud-auth
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
