server:
  port: 8762

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
  main:
    allow-bean-definition-overriding: true

api:
  auth: "http://localhost:8081/"

auth:
  endpoints:
    user: ${api.auth}auth/usercontext
    admin: ${api.auth}auth/admin